services:
  nnmfrontend:
    build:
      dockerfile: Dockerfile
      context: .  # use the current directory
      secrets:
        - GATSBY_MYSHOPIFY_URL
        - SHOPIFY_APP_PASSWORD

    container_name: frontend

    environment:
      - BACKEND_URL=http://nnmbackend:8000

    ports:
      - "80:2000"
    
    command: npm run serve -- -p 2000 -H 0.0.0.0
  
  nnmbackend:
    build:
      context: ./nnmbackend
      secrets:
        - GATSBY_MYSHOPIFY_URL
        - SHOPIFY_STOREFRONT_KEY

    environment:
      - AGENT_URL=http://nnmagent:3000

    ports:
      - "8000:8000"
    command: ["/bin/server"]

  nnmagent:
    build: 
      context: ./nnmagent
    
    environment:
      - BACKEND_URL=http://nnmbackend:3000
    
    ports:
      - "3000:3000"
  
secrets:
  GATSBY_MYSHOPIFY_URL:
    environment: GATSBY_MYSHOPIFY_URL
  SHOPIFY_APP_PASSWORD:
    environment: SHOPIFY_APP_PASSWORD
  SHOPIFY_STOREFRONT_KEY:
    environment: SHOPIFY_STOREFRONT_KEY